package com.mycompany.vrsystem;

public class Vehicles extends javax.swing.JFrame {

    //Creates new form Vehicles
    public Vehicles() {
        initComponents();
        this.setTitle("WELCOME! 'Account name' ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ourVehicle1_SUVMitsubishiMontero = new javax.swing.JLabel();
        ourVehicle2_SedanToyota = new javax.swing.JLabel();
        ourVehicle3_SUVSuzuki = new javax.swing.JLabel();
        ourVehicle4_SUVNissan = new javax.swing.JLabel();
        ourVehicle5_SUVMazdaCX8 = new javax.swing.JLabel();
        ourVehicle6_VanToyotaSuperGrandia = new javax.swing.JLabel();
        ourVehicle7_CoasterToyota = new javax.swing.JLabel();
        ourVehicle8_MinivanKia = new javax.swing.JLabel();
        ourVehicle9_MitsubishiL300 = new javax.swing.JLabel();
        ourVehicle10_SUVFord = new javax.swing.JLabel();
        ourVehiclestxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ourVehicle1_SUVMitsubishiMontero.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle1_SUVMitsubihiMontero.jpg")); // NOI18N
        ourVehicle1_SUVMitsubishiMontero.setText("jLabel1");
        jPanel1.add(ourVehicle1_SUVMitsubishiMontero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 389, 227));

        ourVehicle2_SedanToyota.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle2_SedanToyota.jpg")); // NOI18N
        ourVehicle2_SedanToyota.setText("jLabel2");
        jPanel1.add(ourVehicle2_SedanToyota, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 396, 227));

        ourVehicle3_SUVSuzuki.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle3_SUVSuzuki.jpg")); // NOI18N
        ourVehicle3_SUVSuzuki.setText("jLabel3");
        jPanel1.add(ourVehicle3_SUVSuzuki, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 534, 389, 227));

        ourVehicle4_SUVNissan.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle4_SUVNissan.jpg")); // NOI18N
        ourVehicle4_SUVNissan.setText("jLabel4");
        jPanel1.add(ourVehicle4_SUVNissan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 396, 227));

        ourVehicle5_SUVMazdaCX8.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle5_SUVMazdaCX8.jpg")); // NOI18N
        ourVehicle5_SUVMazdaCX8.setText("jLabel5");
        jPanel1.add(ourVehicle5_SUVMazdaCX8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 910, 389, 227));

        ourVehicle6_VanToyotaSuperGrandia.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle6_VanToyotaSuperGrandia.jpg")); // NOI18N
        ourVehicle6_VanToyotaSuperGrandia.setText("jLabel6");
        jPanel1.add(ourVehicle6_VanToyotaSuperGrandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 910, 396, 227));

        ourVehicle7_CoasterToyota.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle7_CoasterToyota.jpg")); // NOI18N
        ourVehicle7_CoasterToyota.setText("jLabel7");
        jPanel1.add(ourVehicle7_CoasterToyota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1260, 389, 227));

        ourVehicle8_MinivanKia.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle8_MinivanKia.jpg")); // NOI18N
        ourVehicle8_MinivanKia.setText("jLabel8");
        jPanel1.add(ourVehicle8_MinivanKia, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1260, 396, 227));

        ourVehicle9_MitsubishiL300.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle9_MitsubishiL300.jpg")); // NOI18N
        ourVehicle9_MitsubishiL300.setText("jLabel9");
        jPanel1.add(ourVehicle9_MitsubishiL300, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1640, 389, 227));

        ourVehicle10_SUVFord.setIcon(new javax.swing.ImageIcon("C:\\Users\\baldo\\Downloads\\Car Rental Images\\ourVehicle10_SUVFord.jpg")); // NOI18N
        ourVehicle10_SUVFord.setText("jLabel10");
        jPanel1.add(ourVehicle10_SUVFord, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1640, 396, 230));

        ourVehiclestxt.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        ourVehiclestxt.setText("Choose Vehicle");
        jPanel1.add(ourVehiclestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 31, 267, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("₱2,500.00 per day");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1200, 214, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("SUV | Mitsubishi Montero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 298, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Sedan | Toyota Altis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 242, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("₱2,500.00 per day");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 214, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("SUV | SUZUKI XL7");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 767, 226, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("₱2,800.00 per day");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 214, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("SUV | NISSAN TERRA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 770, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("₱3,000.00 per day");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 830, 214, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("SUV | Mazda CX8");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1140, 226, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("₱2,500.00 per day");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 830, 214, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setText("VAN | TOYOTA SUPER GRANDIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("₱3,500.00 per day");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1200, 214, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setText("COASTER | TOYOTA COASTER");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1490, 353, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel14.setText("MINIVAN | KIA CARNIVAL");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1490, 226, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("₱4,000.00 per day");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1550, 214, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("₱2,500.00 per day");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1550, 214, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel17.setText("Van | Mitsubishi L300");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1880, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("₱3,500.00 per day");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1940, 214, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel19.setText("SUV | FORD NEXTGEN EVEREST");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1880, 370, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("₱2,800.00 per day");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1940, 214, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("We have the best cars for you to choose.");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 85, 365, 43));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("RENT NOW!");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 101, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("RENT NOW!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("RENT NOW!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 860, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("RENT NOW!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 860, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("RENT NOW!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1230, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setText("RENT NOW!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1220, -1, -1));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setText("RENT NOW!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1580, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setText("RENT NOW!");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1580, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Mitsubishi");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Toyota");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Suzuki");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 800, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Nissan");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 800, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Mazda");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1170, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Toyota");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1170, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Toyota");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1520, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Kia");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 1520, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Mitsubishi");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1910, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Ford");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1910, -1, -1));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setText("RENT NOW!");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1960, -1, -1));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setText("RENT NOW!");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1960, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2028, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //to open the FillUpForm after selecting the Rent Now! button
        FillUpForm toFillUpForm = new FillUpForm();
        toFillUpForm.show();
        
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ourVehicle10_SUVFord;
    private javax.swing.JLabel ourVehicle1_SUVMitsubishiMontero;
    private javax.swing.JLabel ourVehicle2_SedanToyota;
    private javax.swing.JLabel ourVehicle3_SUVSuzuki;
    private javax.swing.JLabel ourVehicle4_SUVNissan;
    private javax.swing.JLabel ourVehicle5_SUVMazdaCX8;
    private javax.swing.JLabel ourVehicle6_VanToyotaSuperGrandia;
    private javax.swing.JLabel ourVehicle7_CoasterToyota;
    private javax.swing.JLabel ourVehicle8_MinivanKia;
    private javax.swing.JLabel ourVehicle9_MitsubishiL300;
    private javax.swing.JLabel ourVehiclestxt;
    // End of variables declaration//GEN-END:variables
}
